services:
  backend:
    build:
      context: ./recipe-back
      dockerfile: docker/Dockerfile
    ports:
      - "5182:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=RecipeDB;User ID=sa;Password=recipe-back2025;TrustServerCertificate=True;
    networks:
      - recipe-net

  frontend:
    build:
      context: ./recipe-front
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - recipe-net
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5182/api/Recipes
      - INTERNAL_API_URL=http://backend:8080/api/Recipes
    volumes:
      - ./recipe-front:/app
      - frontend_next:/app/.next
      - /app/node_modules

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=recipe-back2025
      - MSSQL_PID=Developer
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - recipe-net

volumes:
  sqldata:
  frontend_next:

networks:
  recipe-net:
    driver: bridge
