services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=RecipeDB;User ID=sa;Password=asp-demo2025;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=asp-demo2025
      - MSSQL_PID=Developer
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata:
